//! Build script: besides the normal Tauri build, scans the bundled provider
//! SVG directory and emits a Rust table of (provider_id -> svg source) into
//! OUT_DIR. `taskbar_icons` includes the emitted file so the native
//! taskbar strip can rasterise the official brand SVGs with Direct2D. The only
//! supported way to add/remove provider icons is to add/remove
//! `ProviderIcon-<id>.svg` in
//! apps/desktop-tauri/src/components/providers/icons — regeneration happens at
//! build time and a stale build.rs output is overwritten.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();

    // env! is set because Cargo sets CARGO_MANIFEST_DIR to this crate's root
    // (apps/desktop-tauri/src-tauri). The icons live one level up inside the
    // web app source tree: ../src/components/providers/icons.
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest
        .join("..")
        .join("src")
        .join("components")
        .join("providers")
        .join("icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    if !icons_dir.is_dir() {
        panic!(
            "provider icon directory not found at {} — the taskbar icon table cannot be built",
            icons_dir.display()
        );
    }

    let mut entries: Vec<(String, PathBuf)> = fs::read_dir(&icons_dir)
        .expect("read provider icon directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.is_file())
        .filter_map(|path| {
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or_default()
                .to_string();
            let id = name
                .strip_prefix("ProviderIcon-")
                .and_then(|rest| rest.strip_suffix(".svg"))
                .map(str::to_string);
            id.map(|id| (id, path))
        })
        .collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Rebuild if any icon changes so the emitted table never goes stale.
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut out = String::from(
        "// @generated by build.rs — do not edit.
         // provider_id -> official brand SVG source,
         // scanned from apps/desktop-tauri/src/components/providers/icons.
         pub const PROVIDER_ICON_TABLE: &[(&str, &str)] = &[
",
    );
    for (id, path) in &entries {
        // include_str! needs a path literal; a canonical absolute path avoids
        // any cwd ambiguity. Use forward slashes for portability of the source
        // text (Windows accepts escaped backslashes, but forward works too).
        let canon = canonical_display(path);
        out.push_str(&format!("    (\"{id}\", include_str!(r#\"{canon}\"#)),\n"));
    }
    out.push_str(
        "];
",
    );

    let target = out_dir.join("provider_icon_table.rs");
    fs::write(&target, out).expect("write provider_icon_table.rs");
}

/// Emit an absolute path that Rust's include_str! accepts. On Windows a
/// canonical path uses backslashes; include_str! accepts them inside a literal
/// but we normalize to forward slashes to be unambiguous.
fn canonical_display(path: &Path) -> String {
    let canon = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    canon.to_string_lossy().replace('\\', "/")
}
